[2024-05-10T13:50:06.361+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: airflow_dag.clean_scopus manual__2024-05-10T13:48:57.271927+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
